language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "stable"
    - "8.9.4"
sudo: false
env:
  - NO_SANDBOX=true

script:
    - npm test

cache:
  directories:
    - node_modules

addons:
    chrome: stable
